"""empty message

Revision ID: c253b7046065
Revises: 9d40466359ac
Create Date: 2018-07-18 14:35:06.102816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c253b7046065'
down_revision = '9d40466359ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('isactive', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('isdelete', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('permissions', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('token', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['name'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'token')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'permissions')
    op.drop_column('user', 'password')
    op.drop_column('user', 'isdelete')
    op.drop_column('user', 'isactive')
    op.drop_column('user', 'icon')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
